config/routes.rb
Rails.application.routes.draw do
  root to: 'main#index'
  
  resources :employees

  resources :runs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
    validates :name,  presence: true, length: { maximum: 50 }

    before_save { self.email = email.downcase }

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true

    validates :phone_number, length: { maximum: 50 }

    validates :address, length: { maximum: 50 }

    validates :ems_number, length: { maximum: 50 }

    validates :ems_level,  presence: true, length: { maximum: 50 }

    validates :emergency_contact_name, length: { maximum: 50 }

    validates :emergency_contact_number, length: { maximum: 50 }

    validates :hire_date, length: { maximum: 50 }

end

app/models/run.rb
class Run < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pagy::Backend
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
    def index
        @pagy, @employees = pagy(Employee.order (:name))
    end

    def show
        @employee = Employee.find(params[:id])
    end

    def new
        @employee = Employee.new
    end
    
    def edit
        @employee = Employee.find(params[:id])
    end

    def create
        @employee = Employee.new(employee_params)
       
      if @employee.save
        redirect_to @employee
        else
          render 'new'
        end
    end

    def update
        @employee = Employee.find(params[:id])

        if @employee.update(employee_params)
            redirect_to @employee
          else
            render 'edit'
          end
    
    end

    def destroy
        @employee = Employee.find(params[:id])
        @employee.destroy
       
        redirect_to employees_path
      end
       
      private
        def employee_params
          params.require(:employee).permit(:name, :phone_number, :address, :ems_number, :ems_level, :emergency_contact_name, :emergency_contact_number, :email, :hire_date)
        end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/runs_controller.rb
class RunsController < ApplicationController
    def index
        @runs = Run.all
      end
    def show
        @run = Run.find(params[:id])
      end
    
    def new
    end

    def edit
        @run = Run.find(params[:id])
      end

    def create
        @run = Run.new(run_params)
       
        @run.save
        redirect_to @run
      end

    def update
    @run = Run.find(params[:id])

    if @run.update(run_params)
        redirect_to @run
        else
        render 'edit'
        end

    end  

    def destroy
        @run = Run.find(params[:id])
        @run.destroy
       
        redirect_to runs_path
      end
       
      private
        def run_params
          params.require(:run).permit(:run_number, :date, :station, :time_of_call, :onscene, :inservice, :number, :street1, :street2, :category1, :category2, :info, :shift, :name, :a2591, :a2592, :a2551, :a2552, :a2553, :a2571, :a2572, :a2501, :a2502, :a2503, :a2504)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/runs_helper.rb
module RunsHelper
end

app/views/employees/edit.html.erb
<h1>Edit Employee</h1>
<%= form_with(model: @employee, local: true) do |form| %>

  <div class="container">
  <%= render 'shared/error_messages' %>
    <div class="row">
      <div class= "col">
        <p>
          <%= form.label :Name %><br>
          <%= form.text_field :name %>
        </p>
        <p>
          <%= form.label :phone_number, 'Phone Number' %><br>
          <%= form.telephone_field :phone_number %>
        </p>
        <p>
          <%= form.label :Address %><br>
          <%= form.text_field :address %>
        </p>
        <p>
          <%= form.label :ems_level, 'EMS Level' %><br>
          <%= form.select :ems_level, ['', 'N/A', 'Basic', 'Advanced', 'Paramedic']%>
        </p>
        <p>
          <%= form.label :ems_number, 'EMS Number' %><br>
          <%= form.text_field :ems_number %>
        </p>
        
      </div> 
      <div class="col">
        
        <p>
          <%= form.label :emergency_contact_name, 'Emergency Contact' %><br>
          <%= form.text_field :emergency_contact_name %>
        </p>
        <p>
          <%= form.label :emergency_contact_number, 'Emergency Contact Number' %><br>
          <%= form.text_field :emergency_contact_number %>
        </p>
        <p>
          <%= form.label :Email %><br>
          <%= form.email_field :email %>
        </p>
        <p>
          <%= form.label :hire_date, 'Hire Date' %><br>
          <%= form.date_field :hire_date %>
        </p>
        
      </div>
    </div>
  </div>
  <p>
      <%= form.submit %>
    </p>
  
  <% end %>


<%= link_to 'Back', employees_path, class: "btn btn-sm btn-outline-secondary" %>
  
  
  

app/views/employees/index.html.erb
 <div>
<table>
  <tr>
    <h1>Employees</h1>
    <th></th>
  </tr>
  <%= link_to 'New Employee', new_employee_path, class: "btn btn-sm btn-outline-secondary" %>
  
  
  <% @employees.each do |employee| %>
    
    <tr>
      <td><%= employee.name %></td>
      <td><%= employee.phone_number %></td>

      <td><%= link_to 'Show', employee_path(employee), class: "btn btn-sm btn-outline-secondary" %> | </td>
      
      <td><%= link_to 'Delete', employee_path(employee), class: "btn btn-sm btn-outline-secondary",
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>   
  <% end %>  
</table>
</div>
<br>
<%== pagy_bootstrap_nav(@pagy) %>
  <%== pagy_bootstrap_combo_nav_js(@pagy) %>

app/views/employees/new.html.erb
<h1>New Employee</h1>
<%= form_with scope: :employee, url: employees_path, local: true do |form| %>
  
  <div class="container">
  <%= render 'shared/error_messages' %>
    <div class="row">
      <div class= "col">
        <p>
          <%= form.label :Name %><br>
          <%= form.text_field :name %>
        </p>
        <p>
          <%= form.label :phone_number, 'Phone Number' %><br>
          <%= form.telephone_field :phone_number %>
        </p>
        <p>
          <%= form.label :Address %><br>
          <%= form.text_field :address %>
        </p>
        <p>
          <%= form.label :ems_level, 'EMS Level' %><br>
          <%= form.select :ems_level, ['', 'N/A', 'Basic', 'Advanced', 'Paramedic']%>
        </p>
        <p>
          <%= form.label :ems_number, 'EMS Number' %><br>
          <%= form.text_field :ems_number %>
        </p>
        
      </div> 
      <div class="col">
        
        <p>
          <%= form.label :emergency_contact_name, 'Emergency Contact' %><br>
          <%= form.text_field :emergency_contact_name %>
        </p>
        <p>
          <%= form.label :emergency_contact_number, 'Emergency Contact Number' %><br>
          <%= form.text_field :emergency_contact_number %>
        </p>
        <p>
          <%= form.label :Email %><br>
          <%= form.email_field :email %>
        </p>
        <p>
          <%= form.label :hire_date, 'Hire Date' %><br>
          <%= form.date_field :hire_date %>
        </p>
        
      </div>
    </div>
  </div>
   
    <p>
      <%= form.submit %>
    </p>
  <% end %>
  <%= link_to 'Back', employees_path, class: "btn btn-sm btn-outline-secondary" %>

app/views/employees/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>
 
<p>
  <strong>Phone Number:</strong>
  <%= @employee.phone_number %>
</p> 

<p>
  <strong>Address:</strong>
  <%= @employee.address %>
</p> 

<p>
  <strong>EMS Number:</strong>
  <%= @employee.ems_number %>
</p> 

<p>
  <strong>EMS Level:</strong>
  <%= @employee.ems_level %>
</p> 

<p>
  <strong>Emergency Contact Name:</strong>
  <%= @employee.emergency_contact_name %>
</p> 

<p>
  <strong>Emergency Contact Number:</strong>
  <%= @employee.emergency_contact_number %>
</p> 
<p>
  <strong>Email:</strong>
  <%= @employee.email %>
</p> 
<p>
  <strong>Hire Date:</strong>
  <%= @employee.hire_date %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee), class: "btn btn-sm btn-outline-secondary" %> |
<%= link_to 'Back', employees_path, class: "btn btn-sm btn-outline-secondary" %>

app/views/layouts/_footer.html.erb
<footer class="site-footer">
    <div id="content"class="container">
      <p>&copy; 2016 - <%= Time.now.year %> Console Ver. 2.00<br>
      by GEI Web Development</p>
    </div>
  </footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="#" id= "logo">Leeds Fire & Rescue</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/runs">Run Log</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/employees">Employees</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="http://www.crewsense.com/Application/Login/" target="_blank">CrewSense</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://app.targetsolutions.com/auth/index.cfm?action=login.showlogin&customerid=29980&customerpath=leedsalabama" target="_blank">TargetSolutions</a>
          </li>
        </ul> 
      </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Leed Fire</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <%= render 'layouts/header'%>
    <div class="container">
      <%= yield %>
    </div>
      <%= render 'layouts/footer'%>
  </body>
</html>

app/views/runs/edit.html.erb
<h1>Edit Run</h1>

<%= form_with(model: @run, local: true) do |form| %>
  <div class="container">
  <div class="row">
    <div class="col">
      <p>
        <%= form.label :run_number, 'Run Number' %><br>
        <%= form.text_field :run_number %>
      </p>
    
      <p>
        <%= form.label :date %><br>
        <%= form.text_field :date %>
      </p>

      <p>
        <%= form.label :station %><br>
        <%= form.select :station, ['', '1', '2', 'Mutual Aid']%>
      </p>

      <p>
        <%= form.label :time_of_call, 'Time of Call' %><br>
        <%= form.text_field :time_of_call %>
      </p>

      <p>
        <%= form.label :onscene, 'On Scene' %><br>
        <%= form.text_field :onscene %>
      </p>

      <p>
        <%= form.label :inservice %><br>
        <%= form.text_field :inservice %>
      </p>

      <p>
        <%= form.label :shift %><br>
        <%= form.select :shift, ['', 'A', 'B', 'C']%>
      </p>
    </div>
    <div class='col'
      <p>
        <%= form.label :street1, 'Street' %><br>
        <%= form.text_field :street1 %>
      </p>

      <p>
        <%= form.label :street2, 'Cross Street' %><br>
        <%= form.text_field :street2 %>
      </p>

      <p>
        <%= form.label :category1, 'Primary Nature of Call' %><br>
        <%= form.text_field :category1 %>
      </p>

      <p>
        <%= form.label :category2, 'Secondary Nature of Call' %><br>
        <%= form.text_field :category2 %>
      </p>

      <p>
        <%= form.label :info, 'Additional Info' %><br>
        <%= form.text_field :info %>
      </p>

      <p>
        <%= form.label :number %><br>
        <%= form.text_field :number %>
      </p>

      <p>
        <%= form.label :name %><br>
        <%= form.select :name, ['', 'Allred', 
                                    'Akerman',
                                    'Armstrong',
                                    'Blount',
                                    'Borrello',
                                    'Bush',
                                    'Clayton',
                                    'Courington',
                                    'J. Davis',
                                    'P. Davis',
                                    'Doyle',
                                    'Dunsker',
                                    'Ford',
                                    'Green',
                                    'Hannah',
                                    'Harris',
                                    'Holcombe',
                                    'Howard',
                                    'Jenkins',
                                    'Johnson',
                                    'Kearns',
                                    'Mizell',
                                    'Moman',
                                    'Norsworthy',
                                    'Parsons',
                                    'Paterno',
                                    'Roberson',
                                    'Rossetti',
                                    'Shell',
                                    'Sims',
                                    'J. Smith',
                                    'Smotherman',
                                    'Templeton',
                                    'Tipton',
                                    'Velez-Ruiz',
                                    'C. Williams',
                                    'Other']%>
      </p>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-sm"
      <p>
        <%= form.check_box :a2591 %>
        <%= form.label :a2591, '2591' %><br>   
      </p>
      <p>
        <%= form.check_box :a2592 %>
        <%= form.label :a2592, '2592' %><br>  
      </p>
      <p>
        <%= form.check_box :a2551 %>
        <%= form.label :a2551, '2551' %><br>
      </p>
    </div>
    <div class="col-sm">
      <p>
        <%= form.check_box :a2552 %>
        <%= form.label :a2552, '2552' %><br>
      </p>
      <p>
        <%= form.check_box :a2553 %>
        <%= form.label :a2553, '2553' %><br> 
      </p>
      <p>
        <%= form.check_box :a2571 %>
        <%= form.label :a2571, '2571' %><br>
      </p>
    </div>
    <div class="col-sm">
      <p>
        <%= form.check_box :a2572 %>
        <%= form.label :a2572, '2572' %><br>
      </p>
      <p>
        <%= form.check_box :a2501 %>
        <%= form.label :a2501, '2501' %><br>
      </p>
      <p>
        <%= form.check_box :a2502 %>
        <%= form.label :a2502, '2502' %><br>
      </p>
    </div>
    <div class="col-sm">
      <p>
        <%= form.check_box :a2503 %>
        <%= form.label :a2503, '2503' %><br>
      </p>
      <p>
        <%= form.check_box :a2504 %>
        <%= form.label :a2504, '2504' %><br>  
      </p>
    </div>
   </div>
  </div>  
<div class="container">
  <p>
    <%= form.submit %>
  </p>
</div>    
  <% end %>
  <%= link_to 'Back', runs_path, class: "btn btn-sm btn-outline-secondary" %>

app/views/runs/index.html.erb
<h1>Runs</h1>
 
<table>
  <tr>
    <th>Run Number</th>
    <th>Date</th>
    <th></th>
  </tr>
  <%= link_to 'New Run', new_run_path, class: "btn btn-sm btn-outline-secondary" %>
  <% @runs.each do |run| %>
    <tr>
      <td><%= run.run_number %></td>
      <td><%= run.date %></td>
      <td><%= link_to 'Show', run_path(run), class: "btn btn-sm btn-outline-secondary" %> | </td>
      <td><%= link_to 'Delete', run_path(run), class: "btn btn-sm btn-outline-secondary",
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/runs/new.html.erb
<h1>New Run</h1>

<%= form_with scope: :run, url: runs_path, local: true do |form| %>
  <div class="container">
    <div class="row">
      <div class="col">
        <p>
          <%= form.label :run_number, 'Run Number' %><br>
          <%= form.text_field :run_number %>
        </p>
      
        <p>
          <%= form.label :date %><br>
          <%= form.text_field :date %>
        </p>

        <p>
          <%= form.label :station %><br>
          <%= form.select :station, ['', '1', '2', 'Mutual Aid']%>
        </p>

        <p>
          <%= form.label :time_of_call, 'Time of Call' %><br>
          <%= form.text_field :time_of_call %>
        </p>

        <p>
          <%= form.label :onscene, 'On Scene' %><br>
          <%= form.text_field :onscene %>
        </p>

        <p>
          <%= form.label :inservice %><br>
          <%= form.text_field :inservice %>
        </p>

        <p>
          <%= form.label :shift %><br>
          <%= form.select :shift, ['', 'A', 'B', 'C']%>
        </p>
      </div>
      <div class='col'
        <p>
          <%= form.label :street1, 'Street' %><br>
          <%= form.select :street1, ['', '10th Court', 
                                        '10th Street',
                                        '11th Court',
                                        '11th Street'] %>
        </p>

        <p>
          <%= form.label :street2, 'Cross Street' %><br>
          <%= form.text_field :street2 %>
        </p>

        <p>
          <%= form.label :category1, 'Primary Nature of Call' %><br>
          <%= form.text_field :category1 %>
        </p>

        <p>
          <%= form.label :category2, 'Secondary Nature of Call' %><br>
          <%= form.text_field :category2 %>
        </p>

        <p>
          <%= form.label :info, 'Additional Info' %><br>
          <%= form.text_field :info %>
        </p>

        <p>
          <%= form.label :number %><br>
          <%= form.text_field :number %>
        </p>

        <p>
          <%= form.label :name %><br>
          <%= form.select :name, ['', 'Allred', 
                                      'Akerman',
                                      'Armstrong',
                                      'Blount',
                                      'Borrello',
                                      'Bush',
                                      'Clayton',
                                      'Courington',
                                      'J. Davis',
                                      'P. Davis',
                                      'Doyle',
                                      'Dunsker',
                                      'Ford',
                                      'Green',
                                      'Hannah',
                                      'Harris',
                                      'Holcombe',
                                      'Howard',
                                      'Jenkins',
                                      'Johnson',
                                      'Kearns',
                                      'Mizell',
                                      'Moman',
                                      'Norsworthy',
                                      'Parsons',
                                      'Paterno',
                                      'Roberson',
                                      'Rossetti',
                                      'Shell',
                                      'Sims',
                                      'J. Smith',
                                      'Smotherman',
                                      'Templeton',
                                      'Tipton',
                                      'Velez-Ruiz',
                                      'C. Williams',
                                      'Other']%>
        </p>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-sm"
        <p>
          <%= form.check_box :a2591 %>
          <%= form.label :a2591, '2591' %><br>   
        </p>
        <p>
          <%= form.check_box :a2592 %>
          <%= form.label :a2592, '2592' %><br>  
        </p>
        <p>
          <%= form.check_box :a2551 %>
          <%= form.label :a2551, '2551' %><br>
        </p>
      </div>
      <div class="col-sm">
        <p>
          <%= form.check_box :a2552 %>
          <%= form.label :a2552, '2552' %><br>
        </p>
        <p>
          <%= form.check_box :a2553 %>
          <%= form.label :a2553, '2553' %><br> 
        </p>
        <p>
          <%= form.check_box :a2571 %>
          <%= form.label :a2571, '2571' %><br>
        </p>
      </div>
      <div class="col-sm">
        <p>
          <%= form.check_box :a2572 %>
          <%= form.label :a2572, '2572' %><br>
        </p>
        <p>
          <%= form.check_box :a2501 %>
          <%= form.label :a2501, '2501' %><br>
        </p>
        <p>
          <%= form.check_box :a2502 %>
          <%= form.label :a2502, '2502' %><br>
        </p>
      </div>
      <div class="col-sm">
        <p>
          <%= form.check_box :a2503 %>
          <%= form.label :a2503, '2503' %><br>
        </p>
        <p>
          <%= form.check_box :a2504 %>
          <%= form.label :a2504, '2504' %><br>  
        </p>
      </div>
     </div>
    </div>  
<div class="container">
    <p>
      <%= form.submit %>
    </p>
</div>    
  <% end %>
  <%= link_to 'Back', runs_path, class: "btn btn-sm btn-outline-secondary" %>

app/views/runs/show.html.erb
<p>
  <strong>Run Number:</strong>
  <%= @run.run_number %>
</p>
 
<p>
  <strong>Date:</strong>
  <%= @run.date %>
</p>

<p>
  <strong>Station:</strong>
  <%= @run.station %>
</p>
 
<p>
  <strong>Time of Call:</strong>
  <%= @run.time_of_call %>
</p>

<p>
  <strong>On Scene:</strong>
  <%= @run.onscene %>
</p>
 
<p>
  <strong>Inservice:</strong>
  <%= @run.inservice %>
</p>
<p>
  <strong>Number:</strong>
  <%= @run.number %>
</p>
 
<p>
  <strong>Street:</strong>
  <%= @run.street1 %>
</p>

<p>
  <strong>Cross Street:</strong>
  <%= @run.street2 %>
</p>
 
<p>
  <strong>Primary Nature of Call:</strong>
  <%= @run.category1 %>
</p>

<p>
  <strong>Secondary Nature of Call:</strong>
  <%= @run.category2 %>
</p>
 
<p>
  <strong>Additional Info:</strong>
  <%= @run.info %>
</p>

<p>
  <strong>Shift:</strong>
  <%= @run.shift %>
</p>
 
<p>
  <strong>Name:</strong>
  <%= @run.name %>
</p>

<p>
  <strong>2591:</strong>
  <%= @run.a2591 %>
</p>
 
<p>
  <strong>2592:</strong>
  <%= @run.a2592 %>
</p>

<p>
  <strong>2551:</strong>
  <%= @run.a2551 %>
</p>
 
<p>
  <strong>2552:</strong>
  <%= @run.a2552 %>
</p>

<p>
  <strong>2553:</strong>
  <%= @run.a2553 %>
</p>
 
<p>
  <strong>2571:</strong>
  <%= @run.a2571 %>
</p>

<p>
  <strong>2572:</strong>
  <%= @run.a2572 %>
</p>
 
<p>
  <strong>2501:</strong>
  <%= @run.a2501 %>
</p>

<p>
  <strong>2502:</strong>
  <%= @run.a2502 %>
</p>
 
<p>
  <strong>2503:</strong>
  <%= @run.a2503 %>
</p>

<p>
  <strong>2504:</strong>
  <%= @run.a2504 %>
</p>
 

<%= link_to 'Edit', edit_run_path(@run), class: "btn btn-sm btn-outline-secondary" %> |
<%= link_to 'Back', runs_path, class: "btn btn-sm btn-outline-secondary" %>

app/views/shared/_error_messages.html.erb
<% if @employee.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@employee.errors.count, "error") %>.
    </div>
    <ul>
    <% @employee.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>